// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var count;
    count = 0;
    return $('.board-cell').on('click', function(e) {
      var mark;
      mark = count % 2 === 0 ? 'x' : 'o';
      if ($(this).text() === '') {
        $(this).text(mark);
        $(this).addClass(mark);
        return count += 1;
      }
    });
  });

}).call(this);

//# sourceMappingURL=game.map
